### ISSUE TITLE
Wrong title in README?

### ISSUE THREAD

**Issue by arboleya** [csupnig/ta-lib#1]
I was wondering where this `gulp-angular-filesort` title came from, in the project README file. :)

**Comment by csupnig** [comment]
Oh… thanks for the hint ;)

-- 
Christopher Supnig
Have a look at my blog at https://www.supnig.com 

On 11 March 2016 at 17:01:12, arboleya (notifications@github.com) wrote:

I was wondering where this gulp-angular-filesort title came from, in the project README file. :)
